### PR TITLE
Added documentation

### PR DESCRIPTION
**Pull request by Illizian**
Adds documentation for implemented methods from the Box API.

(please note: this is upto commit b7dcd64, and therefore does not include your recent work on Users, Groups, Search, Tasks etc.)

### CODE REVIEW

**Comment by henrikromby** [comment]
Hi Alex! Thanks for all this, I'll pull it in when I get home :-)

I did think about changing the signature of the majority of the methods here to always have the OAuth token first, but I'll make sure to update your documentation accordingly. Do you agree that we should streamline these signatures, or should we keep them as they are? (they aren't consistent at the moment).

**Comment by Illizian** [comment]
No worries! It helped me to get a picture of the state of completion.

We should definitely look to standardise where possible, so I agree the
token should be in the same place. Alternatively this could be set
somewhere and use getters and setters for it.

On that note, do you think the oAuth & refreshing tokens is in scope for
this?

**Comment by Illizian** [comment]
Latest documentation is now in.

Do you think a coverage doc would be helpful? (coverage of the box api not tests)

**Comment by henrikromby** [comment]
Cool!

Yeah, I already have a Numbers document with the progress in it. How do we structure it best here on GitHub?

**Comment by Illizian** [comment]
I'm now adding it to the docs/README.md file, no need to add another file.

**Comment by henrikromby** [comment]
Cool! Give me an hour or two and I'll pull this in and rework the method signatures. How much more functionality do you think we need before we can tag v1?

**Comment by Illizian** [comment]
I've just added the doc, this currently implements 64/82 available methods.

**Comment by henrikromby** [comment]
I can't figure out how to get the ID of a user's favorites (the collections), we need that to be able to use that section of the API.

**Pull request merged**
