### PR TITLE
Amended composer.json & added a Readme

### PR DESCRIPTION
**Pull request by Illizian**
Firstly, thank you! I tried multiple libraries and manually uploading a file to Box.com with little success and this library worked out-of-the-box!

I had to tinker with the composer.json file in order to get Composer to correctly autoload the classes in Laravel.

I also added a Readme file for reference on how I did that...

### CODE REVIEW

**Comment by henrikromby** [comment]
Wow, thanks so much for submitting a pull request! I'm all new to accepting these, so I'll accept it when I get home and have a chance to figure it out.

Although all of the functionality here is somewhat well-tested, I should note that it is still very pre-alpha and things may break at any time.

But again, thanks for contributing! So cool :-)

**Comment by henrikromby** [comment]
Should be all good now?

Thanks again for contributing! :-) If you have the time, please consider adding even more functionality -- I believe we are close to feature parity with the API :-)

**Comment by Illizian** [comment]
Cheers, I'll give it a go in the morning.

I'd be happy to if I get the chance, do you have a list of outstanding functionality?

**Comment by henrikromby** [comment]
I am going through their API docs one item at a time: https://developers.box.com/docs/#folders

I'm currently working on the user functionality, so the four big remaining items are Search, Groups, Tasks and Collections. There are also a couple of smaller sub-items that I've skipped along the way, but I think we can add them after submitting the first version to Packagist.

Again, thank you so much for helping out. Even though it's a simple and very clean API, there's a lot of functionality to hook into :-)

**Comment by Illizian** [comment]
I'm working on a project that will need to make use of a great deal of their API (certainly the Search and Collections) so I'll definitely be helping out ;)

**Comment by henrikromby** [comment]
That's cool :-) If you have any questions or comments regarding the way I've set up Behat or PHPSpec, please ask and I'll do my best to try and explain the choices made there :-)

**Pull request merged**
